== gymy-seminar

image:https://github.com/oskopek/gymy-seminar/workflows/Java%20CI%20with%20Maven/badge.svg["Java CI with Maven", link="https://github.com/oskopek/gymy-seminar/actions?query=workflow%3A%22Java+CI+with+Maven%22"]

A seminar grouping system.

=== Building
* *Recommended*: `mvn clean install -DskipTests`
* To run *unit tests*: `mvn clean install`
* To *clean*, run: `mvn clean`

=== Running releases

* Download the latest release (jar with dependencies)
* Run it with `java -jar gymy-seminare-VERSION-jar-with-dependencies.jar`

=== Getting help

Don't be afraid to https://github.com/oskopek/gymy-seminar/issues[open an issue].

=== Contributing
*Everyone* is encouraged to help improve this project.

Here are some ways *you* can contribute:

* by using alpha, beta, and pre-release versions
* by reporting bugs
* by suggesting new features
* by implementing planned features
* by translating to a new language
* by writing or editing documentation
* by writing specifications
* by writing code (*no patch is too small*: fix typos, add comments, clean up inconsistent whitespace)
* by refactoring code
* by closing https://github.com/oskopek/gymy-seminar/issues[issues]
* by reviewing patches

=== Submitting an Issue
We use the https://github.com/oskopek/gymy-seminar/issues[GitHub issue tracker] to track bugs and features. Before
submitting a bug report or feature request, check to make sure it hasn't
already been submitted. When submitting a bug report, please include a https://gist.github.com/[Gist]
that includes a stack trace and any details that may be necessary to reproduce
the bug, including your Java version and operating system.

=== Submitting a Pull Request
. http://help.github.com/fork-a-repo/[Fork the repository]
. http://learn.github.com/p/branching.html[Create a topic branch]
. Implement your feature or bug fix
. If applicable, add tests for your feature or bug fix
. Run `mvn clean install`
. If the tests fail, return to step 3 and 4
. Add, commit, and push your changes
. http://help.github.com/send-pull-requests/[Submit a pull request]
